import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { module } = body;

    // Simulate API delay
    await new Promise((resolve) => setTimeout(resolve, 1000));

    let content = '';

    switch (module) {
      case 'pulse':
        content = generateSecurityPulseContent(body);
        break;
      case 'phishing':
        content = generatePhishingContent(body);
        break;
      case 'awareness':
        content = generateAwarenessContent(body);
        break;
      default:
        return NextResponse.json(
          { error: 'Invalid module specified' },
          { status: 400 }
        );
    }

    return NextResponse.json({ content });
  } catch (error) {
    console.error('API Error:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

function generateSecurityPulseContent(data: {
  topic: string;
  outputFormat: string;
}): string {
  const { topic, outputFormat } = data;
  const topicText = topic || 'general cyber security threats';

  if (outputFormat === 'Email draft') {
    return `Subject: Security Update - ${topicText}

Dear Team,

I wanted to bring to your attention recent developments in ${topicText}. Here's a summary of the key points:

1. **Threat Overview**: Multiple organisations have reported increased activity related to ${topicText} in the past week.

2. **Impact Assessment**: These incidents have resulted in operational disruptions and potential data exposure for affected organisations.

3. **Recommended Actions**:
   - Review and update access controls
   - Enable multi-factor authentication where possible
   - Report any suspicious activity to IT immediately
   - Stay vigilant when opening emails or clicking links

4. **Additional Resources**: Please refer to our security portal for detailed guidance and training materials.

If you have any questions or concerns, please don't hesitate to reach out to the security team.

Stay safe,
Security Team

---
⚠️ DISCLAIMER: This content was generated by ASTRA (POC). Please review before distribution.`;
  } else if (outputFormat === 'Viva post') {
    return `🔒 Security Alert: ${topicText}

Recent intelligence suggests increased activity around ${topicText}. Here's what you need to know:

📌 What's happening?
Multiple organisations have observed suspicious activity related to ${topicText}.

📌 What should you do?
✅ Review your access controls
✅ Enable MFA if you haven't already
✅ Report anything suspicious to IT
✅ Think before you click

📌 Need help?
Contact the security team or visit our security portal.

#CyberSecurity #StaySecure #InfoSec

---
⚠️ Generated by ASTRA (POC) - Review before posting`;
  } else {
    return `Security Update: ${topicText}

• Recent surge in ${topicText}
• Multiple organisations affected
• Action required: Review security settings
• Enable MFA and report suspicious activity
• Contact security team for guidance

⚠️ Generated by ASTRA (POC) - Review before use`;
  }
}

function generatePhishingContent(data: {
  scenario: string;
  sophistication: string;
  includeRedFlags: boolean;
}): string {
  const { scenario, sophistication, includeRedFlags } = data;

  let redFlagsNote = '';
  if (includeRedFlags) {
    redFlagsNote = `

🚩 RED FLAGS INCLUDED FOR TRAINING:
- Generic greeting instead of personalised name
- Urgent language designed to bypass critical thinking
- Request to take action immediately
- Link text that doesn't match actual URL
`;
  }

  if (scenario === 'Password reset request') {
    return `From: IT Support <it-support@company-security-verify.com>
To: [User Email]
Subject: ${sophistication.includes('Basic') ? 'URGENT!!!' : 'Security Alert:'} Password Reset Required

${sophistication.includes('Basic') ? 'DEAR USER,' : 'Hello,'}

${sophistication.includes('Advanced') ? 'Our security systems have detected unusual login activity on your account from an unrecognised device in [User Location]. As a precautionary measure, we need you to verify your account credentials.' : 'Your password has expired and must be reset immediately to avoid account suspension.'}

${sophistication.includes('Basic') ? 'CLICK HERE NOW: http://password-reset-urgent.com' : 'Please click the link below to complete the verification process within 24 hours:'}
${sophistication.includes('Basic') ? '' : 'https://company-portal.com/verify-account'}

${sophistication.includes('Advanced') ? 'If you did not attempt to log in, please contact IT support immediately.' : 'Failure to reset your password will result in immediate account deactivation.'}

${sophistication.includes('Advanced') ? 'Best regards,' : 'Thank you,'}
${sophistication.includes('Advanced') ? 'IT Security Team' : 'IT Support'}
${sophistication.includes('Advanced') ? 'Internal Extension: 1234' : ''}
${redFlagsNote}
---
⚠️ TRAINING SIMULATION - Generated by ASTRA (POC)
⚠️ This is a SIMULATED phishing email for training purposes only
⚠️ Review and approve with security team before use`;
  } else if (scenario === 'IT support alert') {
    return `From: IT Helpdesk <helpdesk@company-it.com>
To: [User Email]
Subject: System Maintenance Required - Action Needed

${sophistication.includes('Basic') ? 'Dear Employee,' : 'Hi [Name],'}

${sophistication.includes('Advanced') ? 'We are conducting scheduled system maintenance this weekend. To ensure your account remains accessible during the update, we need you to verify your current system configuration.' : 'Your computer requires urgent security updates. Install now to avoid system failure.'}

${sophistication.includes('Basic') ? 'Download the patch: http://system-update-now.net/install.exe' : 'Please log in to the IT portal and run the verification tool:'}
${sophistication.includes('Basic') ? '' : 'https://company-portal.com/it/verify-system'}

${sophistication.includes('Advanced') ? 'This maintenance window is scheduled for Saturday, 02:00-06:00 GMT. Your cooperation is appreciated.' : 'Install within 2 hours or your computer will be disconnected from the network.'}

${sophistication.includes('Advanced') ? 'Thanks,' : 'Regards,'}
IT Support Team
${sophistication.includes('Advanced') ? 'Ticket #12345' : ''}
${redFlagsNote}
---
⚠️ TRAINING SIMULATION - Generated by ASTRA (POC)
⚠️ This is a SIMULATED phishing email for training purposes only
⚠️ Review and approve with security team before use`;
  } else {
    return `From: ${scenario} Team <noreply@company.com>
To: [User Email]
Subject: ${scenario} - Action Required

Hello,

This is a simulated phishing email for the scenario: "${scenario}"
Sophistication level: ${sophistication}

[Content would be generated here based on the scenario type]

Key elements:
- Realistic sender address
- Urgent call to action
- Link to fake login page
- Social engineering tactics
${redFlagsNote}
---
⚠️ TRAINING SIMULATION - Generated by ASTRA (POC)
⚠️ This is a SIMULATED phishing email for training purposes only
⚠️ Review and approve with security team before use`;
  }
}

function generateAwarenessContent(data: {
  sourceUrl: string;
  sourceText: string;
  contentType: string;
  tone: string;
}): string {
  const { sourceUrl, sourceText, contentType, tone } = data;
  const source = sourceUrl || sourceText || 'recent security news';

  if (contentType === 'Email to staff') {
    return `Subject: Important Security Awareness Update

Dear Colleagues,

I wanted to share an important security update based on ${sourceUrl ? `recent news: ${sourceUrl}` : 'recent security developments'}.

**What's Happening:**
${sourceText ? sourceText.substring(0, 200) + '...' : 'Security researchers have identified new tactics being used by threat actors to compromise organisational systems.'}

**Why It Matters:**
These developments highlight the importance of maintaining vigilance in our day-to-day activities. Even small oversights can create security vulnerabilities.

**What You Can Do:**
1. Stay alert to suspicious emails and messages
2. Verify requests for sensitive information
3. Keep your software and systems up to date
4. Report anything unusual to the security team

**Questions?**
If you're unsure about anything security-related, it's always better to ask. Contact the security team at [security@company.com].

${tone === 'Professional' ? 'Best regards,' : tone === 'Conversational' ? 'Stay safe!' : tone === 'Urgent' ? 'Immediate attention required.' : 'Remember: Security is everyone\'s responsibility.'}

Security Awareness Team

${sourceUrl ? `\n📎 Source: ${sourceUrl}` : ''}

---
⚠️ Generated by ASTRA (POC) - Review before distribution`;
  } else if (contentType === 'Blog/Viva post') {
    return `🔒 Security Awareness: Learn from Recent Events

We want to keep you informed about ${sourceUrl ? 'a recent security incident' : 'important security developments'} that highlights key lessons for all of us.

**The Situation:**
${sourceText ? sourceText.substring(0, 300) + '...' : 'Recent reports show that organisations are facing increasingly sophisticated security challenges.'}

**Key Takeaways:**
✅ Always verify before you trust
✅ Question unexpected requests
✅ Use strong, unique passwords
✅ Enable multi-factor authentication
✅ Report suspicious activity immediately

**Your Role:**
Security is a team effort. By staying informed and following best practices, you help protect our organisation and your colleagues.

${tone === 'Professional' ? '📚 For more information, visit our security portal.' : tone === 'Conversational' ? '💬 Got questions? Drop us a message!' : tone === 'Urgent' ? '⚠️ Act now to protect yourself and the organisation.' : '🎓 Learn more through our security training resources.'}

${sourceUrl ? `\n🔗 Read more: ${sourceUrl}` : ''}

#SecurityAwareness #CyberSecurity #StaySafe

---
⚠️ Generated by ASTRA (POC) - Review before posting`;
  } else if (contentType === 'Poster-style text') {
    return `🔒 SECURITY AWARENESS 🔒

${sourceUrl ? '📰 RECENT NEWS HIGHLIGHTS:' : '📢 IMPORTANT SECURITY UPDATE'}

${sourceText ? sourceText.substring(0, 150) : 'New security threats require your attention'}

🛡️ PROTECT YOURSELF:
✓ Think before you click
✓ Verify requests
✓ Use strong passwords
✓ Enable MFA
✓ Report suspicious activity

${tone === 'Urgent' ? '⚠️ ACTION REQUIRED NOW ⚠️' : '💡 STAY SECURE, STAY SAFE'}

Questions? Contact: security@company.com

${sourceUrl ? `Source: ${sourceUrl}` : ''}

---
⚠️ Generated by ASTRA (POC) - Review before use`;
  } else {
    return `🔒 Security Update

${sourceText ? sourceText.substring(0, 200) : 'Stay informed about the latest security developments.'}

${tone === 'Professional' ? '📌 Professional advice:' : tone === 'Conversational' ? '💬 Quick tip:' : tone === 'Urgent' ? '⚠️ URGENT:' : '📚 Did you know?'}

Always verify before trusting. Stay vigilant. Report suspicious activity.

${sourceUrl ? `\nLearn more: ${sourceUrl}` : ''}

#CyberSecurity #InfoSec #SecurityAwareness

---
⚠️ Generated by ASTRA (POC) - Review before posting`;
  }
}
